### ISSUE TITLE
Cannot minimize to tray with the snap application

### ISSUE THREAD

**Issue by Kabouik** [snapcrafters/mattermost-desktop#12]
Minimize to tray works fine with the non-snap desktop client, but the option cannot be checked in the snap version (it is there, but cannot be enabled).

Mentioned by another user in #6 as well.

**Comment by galgalesh** [comment]
This seems to be fixed by https://github.com/snapcrafters/mattermost-desktop/pull/17

Note that you first need to enable "show icon in the notification area" before "leave app running in notification area.." becomes enabled.
