### ISSUE TITLE
Theme issues -- cannot see menu

### ISSUE THREAD

**Issue by skewty** [snapcrafters/mattermost-desktop#19]
Using fresh (all defaults) install of Ubuntu 19.04 I installed mattermost from snap and the menu items on the menu bar are not visible.
![Screenshot from 2019-04-03 23-41-00](https://user-images.githubusercontent.com/9087223/55534873-55f2ac00-566a-11e9-904b-ba9adb59249a.png)

**Comment by galgalesh** [comment]
Thanks for the bug report!

This is an upstream bug in Mattermost Desktop itself due to an electron issue. It should be fixed in the next major release.

**Comment by galgalesh** [comment]
This should be fixed in the latest version. Please reopen the issue if you still experience it.
