### ISSUE TITLE
EFILE in dns.js despite local DNS working 

### ISSUE THREAD

**Issue by lestephane** [snapcrafters/mattermost-desktop#21]
```text
~$ sudo snap install mattermost-desktop
...
~$ mattermost-desktop 
dns.js:246
    this._handle = new ChannelWrap();
                   ^

Error: EFILE
    at new Resolver (dns.js:246:20)
    at dns.js:377:25
    at dns.js:431:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at net.js:45:13
    at net.js:1730:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at internal/child_process.js:6:13
```
Dns is running

```bash
~$ cat /etc/resolv.conf
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 127.0.3.1

~$ netstat -tulpen | grep 127.0.3.1
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 127.0.3.1:53            0.0.0.0:*               LISTEN      0          26547       -               
udp        0      0 127.0.3.1:53            0.0.0.0:*                           0          26546       -     

```
No suspect entries in dnscrypt-proxy blocked queries log files...

**Comment by galgalesh** [comment]
What distribution and version are you using? Does mattermost work of you
use the desktop file (from the launcher or start menu)?

**Comment by lestephane** [comment]
Sorry for the delayed response. I'm on Ubuntu 16.04.3 LTS and it's happening with mattermost-desktop 4.2.3. Also happening when launching it through the menu item (no application comes up, so i suppose it's because of this same error). Let me know if you need more info

**Comment by galgalesh** [comment]
Hm, I just tried it in an Ubuntu 16.04 VM and I don't have any issues:

![image](https://user-images.githubusercontent.com/1492981/64131872-dd844880-cdcb-11e9-93df-769272f3a75c.png)

Can you see if you have the same issue when you install Mattermost using their unofficial `.deb` installer? https://github.com/mattermost/desktop/releases/tag/v4.2.3

**Comment by lestephane** [comment]
With the deb installer I get this error:

```text
$ mattermost-desktop 
Failed to read or upgrade config.json { Error: ENOENT: no such file or directory, open '/home/lestephane/.config/Mattermost/config.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:538:29)
    at Object.readFileSync (/opt/Mattermost/resources/app.asar/main_bundle.js:20197:73)
    at Object.<anonymous> (/opt/Mattermost/resources/app.asar/main_bundle.js:197:70)
    at __webpack_require__ (/opt/Mattermost/resources/app.asar/main_bundle.js:20:30)
    at /opt/Mattermost/resources/app.asar/main_bundle.js:69:18
    at Object.<anonymous> (/opt/Mattermost/resources/app.asar/main_bundle.js:72:10)
    at Object.<anonymous> (/opt/Mattermost/resources/app.asar/main_bundle.js:27806:3)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/lestephane/.config/Mattermost/config.json' }
Clear cache after update
```
But the application does start
![image](https://user-images.githubusercontent.com/5460884/64239813-969c6d00-cf09-11e9-98b9-f955dbc3f26d.png)

**Comment by galgalesh** [comment]
I can't reproduce this error on Ubuntu 16.04. Do you have a non-default DNS setup or do you know any other non-default configuration that might help me reproduce this issue?

**Comment by lestephane** [comment]
Hmm indeed I was using a [funky dns setup](https://forum.snapcraft.io/t/apparmor-denied-on-etc-resolvconf-resolv-conf-d-head-read-causes-dns-resolution-to-fail-despite-the-use-of-the-network-interface/13933/6), I know have fixed it, and mattermost-desktop installs and starts correctly.
