### ISSUE TITLE
Failed to access your camera

### ISSUE THREAD

**Issue by fraillt** [snapcrafters/mattermost-desktop#35]
Camera is not accessable, here is what snap connections looks like:
```bash
sudo snap connections mattermost-desktop
Interface                 Plug                                       Slot                             Notes
browser-support           mattermost-desktop:browser-support         :browser-support                 -
content[gnome-3-28-1804]  mattermost-desktop:gnome-3-28-1804         gnome-3-28-1804:gnome-3-28-1804  -
content[gtk-3-themes]     mattermost-desktop:gtk-3-themes            gtk-common-themes:gtk-3-themes   -
content[icon-themes]      mattermost-desktop:icon-themes             gtk-common-themes:icon-themes    -
content[sound-themes]     mattermost-desktop:sound-themes            gtk-common-themes:sound-themes   -
desktop                   mattermost-desktop:desktop                 :desktop                         -
desktop-legacy            mattermost-desktop:desktop-legacy          :desktop-legacy                  -
gsettings                 mattermost-desktop:gsettings               :gsettings                       -
home                      mattermost-desktop:home                    :home                            -
login-session-observe     mattermost-desktop:login-session-observe   -                                -
network                   mattermost-desktop:network                 :network                         -
network-bind              mattermost-desktop:network-bind            :network-bind                    -
opengl                    mattermost-desktop:opengl                  :opengl                          -
pulseaudio                mattermost-desktop:pulseaudio              :pulseaudio                      -
screen-inhibit-control    mattermost-desktop:screen-inhibit-control  :screen-inhibit-control          -
unity7                    mattermost-desktop:unity7                  :unity7                          -
wayland                   mattermost-desktop:wayland                 :wayland                         -
x11                       mattermost-desktop:x11                     :x11                             -
```
I believe there should be a `mattermost-desktop:camera` plug, so that I can add this permission manually, but `sudo snap connect mattermost-desktop:camera` returns this error: `error: snap "mattermost-desktop" has no plug named "camera"`.

**Comment by galgalesh** [comment]
I didn't know Mattermost supported camera?

**Comment by galgalesh** [comment]
I released a version of the snap with the camera plug attached. Since I don't know how video chat in mattermost works, I need your help testing it out.

You can switch to the edge version using `snap refresh mattermost-desktop --edge`. After that, `snap connect mattermost-desktop:camera` should work.

**Comment by galgalesh** [comment]
If you can provide more information about how video chat in mattermost works, I can see if we can request an auto-connection so the permission is automatically granted.

**Comment by fraillt** [comment]
I'm not sure how to help you here...
press the button "Start Jitsi meeting" in the top left corner.
![how_to_start_video_call](https://user-images.githubusercontent.com/8264648/99962292-9e5b6200-2d98-11eb-9e65-b2989e1631c5.png)
then you can press on the "Join Meeting"
![image](https://user-images.githubusercontent.com/8264648/99962413-ce0a6a00-2d98-11eb-8d86-c43974c3d804.png)
and.. thats it :)
![image](https://user-images.githubusercontent.com/8264648/99962584-1b86d700-2d99-11eb-986d-5187fc0874f5.png)

BTW, 
```
snap refresh mattermost-desktop --edge
snap connect mattermost-desktop:camera
```
on edge version it works!

**Comment by galgalesh** [comment]
That's very useful, thanks! Jitsi seems to be an optional server plugin, which is why I couldn't find it. I'll promote that version to stable and see about requesting an auto-connection.
