### ISSUE TITLE
Mattermost Desktop 4.7.0

### ISSUE THREAD

**Issue by ajantiss** [snapcrafters/mattermost-desktop#38]
Seems that Mattermost Desktop has released a 4.7.0 version, do you have any plans to update the snap repo ? Or need help ?

https://github.com/mattermost/desktop/releases/tag/v4.7.0

**Comment by galgalesh** [comment]
@ajantiss This updated version is now available in the edge channel. You can help us by testing it out and letting us know here whether it works.

```
sudo snap refresh --edge mattermost-desktop
```

**Comment by ajantiss** [comment]
Thanks a lot for your responsiveness ! That was amazingly quick !
![mm](https://user-images.githubusercontent.com/6159881/123866444-5d7a8b80-d92d-11eb-9252-9b9205acbc7c.png)

Works like a charm after quick tests, I'll let you know if I get troubles with the snap, but imho should be ok.
