### ISSUE TITLE
Stop supporting i386 arch

### ISSUE THREAD

**Issue by galgalesh** [snapcrafters/mattermost-desktop#44]
With the move to core20, this snap can no longer be built for x86/i386 (32-bit) processors. As of today, there are 19 weekly installed devices on this architecture (out of ~19.000 total installs). I'm wondering what the best path forward is.

Options:

1. If we do nothing, users on x86 will simply not receive updates and the snap will silently get out of date. I don't like this solution, I'd much rather warn users the snap will be unsupported.
2. We could have two branches: a core18 one for x86 and a core20 one for amd64. This gives the best user experience but is a lot of work, and I don't think it is worth it to support just 19 people.
3. We push a final update for i386 which adds a dialog box explaining the snap isn't supported anymore. The dialog box has a "don't show this warning again" option if people want to continue using the unsupported version. I prefer this method because it isn't much effort but users are still notified the snap won't get any updates anymore.

What do y'all think? How has this been handled for other snaps?

**Comment by anonymouse64** [comment]
I vote for 3 personally, I think the maintenance burden of another branch just for i386 for 0.1% of users is not worth it. Additionally, the writing has been on the wall for i386 for a while now...
