### ISSUE TITLE
Update to v5

### ISSUE THREAD

**Issue by boistordu** [snapcrafters/mattermost-desktop#49]
Hi,

Are we going to get the update to v5 at some point or not ?

**Comment by myprs** [comment]
Hi,
would be very much appreciated!
Thanks!

**Comment by svelle** [comment]
Hey there, not familiar with how snap works but 5.0.2 is already on the edge branch. Not sure when it's going into stable and how that is decided though.

**Comment by boistordu** [comment]
Wait, 5.2 is not already stable ? This is the main stable version for windows when you want to download mattermost.
If it was in the main branch then it would not be possible to download it as the main app.
Or do you mean in the snap tree ?

**Comment by svelle** [comment]
I mean the snap tree :)

**Comment by boistordu** [comment]
So I guess if it's only intest branch, that the repo is not maintained anymore then?

**Comment by boistordu** [comment]
@svelle Well I must be really stupid or really blind because I really don't see your testing branch in the snap tree
